version: '3'
services:
  app:
    build: .
    image: romeomaryns/docker-seed
    ports:
      - "8080:8080"
    depends_on:
                - db
                - rabbitmq
  db:
    image: postgres
    env_file: .env-postgres
    volumes:
<<<<<<< HEAD
          - ./data:/var/lib/postgresql/data
=======
          - /c/psql-data:/var/lib/postgresql/data
>>>>>>> d9b2575ff0d3d2d52d346bf86c36fd6f16c3cda6
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"