version: '3'
services:
  web:
    build: .
    image: romeomaryns/docker-seed
    ports:
      - "8080:8080"
    depends_on:
                - db
                - rabbitmq
  db:
    image: postgres
    env_file: .env-postgres
    volumes:
          - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"